apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: {{ .Chart.Name }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}
    app.kubernetes.io/managed-by: helm
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Chart.Name }}
    protocol: {{ .Values.service.ports.protocol }}
    port: {{ .Values.service.ports.port }}