replicas: 3

containers:
  image:
    repository: macmiller/mba-bootcamp-hlg
    tag: '1.1.2'
  ports:
    containerPort: 8080
  resources:
    limits:
      cpu: 100m
      memory: 100Mi

service:
  type: LoadBalancer
  ports:
    protocol: TCP
    port: 8080